import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { CustomCursor, Sidebar } from "@varel-web/components";

const montserratFont = Montserrat({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-montserrat",
  weight: ["300", "400", "500", "600", "700", "800"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={montserratFont.variable}>
      <body>
        <CustomCursor />
        <div className="min-h-screen bg-gray-50 text-[#1F2937] flex">
          <Sidebar />

          {/* Main Content */}
          {children}
        </div>
      </body>
    </html>
  );
}
